Mjolnir-MD/Mjolnir

- mjolnir/core/Observer.hpp
sometimes velocities are also needed to see what happens.
Later we need to enable to customize output format and output filter, in a while.
> add .vel file (the simplest format)

- .travis.yml
- README.md
use recent compilers on Travis.CI for testing.
> Travis recent compilers

- mjolnir/input/read_forcefield.hpp
- mjolnir/input/read_input_file.hpp
- mjolnir/input/read_interaction.hpp
- mjolnir/input/read_observer.hpp
- mjolnir/input/read_potential.hpp
- mjolnir/input/read_simulator.hpp
- mjolnir/input/read_spatial_partition.hpp
- mjolnir/input/read_system.hpp
- mjolnir/input/read_units.hpp
- mjolnir/util/logger.hpp
- simplify logger implementation
- add `LOG_NOTICE` that output to both console and log file
- add `LOG_NOTICE` message to `read_*` functions
> add LOG_NOTICE to show the status

- mjolnir/core/UnderdampedLangevinStepper.hpp
Since it only changes the way to store parameter, it does not change trajectory (tested Lennard-Jones system).
The efficiency does not change significantly (become faster ~0.5% compared to master branch).
The code may become a bit clearer, I think.
> change parameter managing in LangevinStepper

- input/excluded-volume/excluded-volume-langevin.toml
- input/excluded-volume/excluded-volume-system.toml
- input/excluded-volume/excluded-volume.toml
- input/implicit_membrane.toml
- input/lennard-jones/lennard-jones-langevin.toml
- input/sh3_AICG2+.toml
- input/sh3_AICG2+_periodic.toml
- mjolnir/input/read_simulator.hpp
- test/util/make_empty_input.hpp
> rename simulator.scheme -> integrator

- mjolnir/potential/local/FlexibleLocalAnglePotential.hpp
related to #34 .
- make thetas (that are already constant) constexpr.
- rename private variables to make them consistent with input file
- some cosmetic changes
> Refactor flp angle

- mjolnir/core/MolecularDynamicsSimulator.hpp
- mjolnir/core/Observer.hpp
- mjolnir/core/SimulatedAnnealingSimulator.hpp
- mjolnir/core/SteepestDescentSimulator.hpp
- mjolnir/input/read_observer.hpp
- mjolnir/util/progress_bar.hpp
> WIP: control progress bar from input files

- mjolnir/core/AxisAlignedPlane.hpp
- mjolnir/core/ExternalForceField.hpp
- mjolnir/core/ExternalForceInteractionBase.hpp
- mjolnir/core/ForceField.hpp
- mjolnir/core/GlobalForceField.hpp
- mjolnir/core/GlobalInteractionBase.hpp
- mjolnir/core/LocalForceField.hpp
- mjolnir/core/LocalInteractionBase.hpp
- mjolnir/core/NaivePairCalculation.hpp
- mjolnir/core/PeriodicGridCellList.hpp
- mjolnir/core/Plane.hpp
- mjolnir/core/SteepestDescentSimulator.hpp
- mjolnir/core/System.hpp
- mjolnir/core/UnderdampedLangevinIntegrator.hpp
- mjolnir/core/UnlimitedGridCellList.hpp
- mjolnir/core/VelocityVerletIntegrator.hpp
- mjolnir/core/VerletList.hpp
- mjolnir/interaction/BondAngleInteraction.hpp
- mjolnir/interaction/BondLengthInteraction.hpp
- mjolnir/interaction/DihedralAngleInteraction.hpp
- mjolnir/interaction/ExternalDistanceInteraction.hpp
- mjolnir/interaction/GlobalPairInteraction.hpp
- mjolnir/interaction/specialization/GlobalPairExcludedVolumeInteraction.hpp
- mjolnir/interaction/specialization/GlobalPairLennardJonesInteraction.hpp
- mjolnir/interaction/specialization/GlobalPairUniformLennardJonesInteraction.hpp
> WIP: add interface to update margin

- mjolnir/core/MolecularDynamicsSimulator.hpp
- mjolnir/core/Observer.hpp
- mjolnir/core/ObserverBase.hpp
- mjolnir/core/SimulatedAnnealingSimulator.hpp
- mjolnir/core/SteepestDescentSimulator.hpp
- mjolnir/core/XYZObserver.hpp
- mjolnir/input/read_observer.hpp
- test/util/make_empty_input.hpp
> add ObserverBase

- input/excluded-volume/excluded-volume-langevin.toml
- input/implicit_membrane.toml
- input/lennard-jones/lennard-jones-langevin.toml
- input/sh3_AICG2+.toml
- input/sh3_AICG2+_periodic.toml
- mjolnir/input/read_integrator.hpp
- mjolnir/input/read_simulator.hpp
- test/mjolnir/test_read_integrator.cpp
- test/mjolnir/test_read_simulator.cpp
- test/util/make_empty_input.hpp
> Integrator table

- mjolnir/input/read_simulator.hpp
- test/mjolnir/test_read_simulator.cpp
> change scheduler settings

- mjolnir/core/PeriodicGridCellList.hpp
- mjolnir/core/Plane.hpp
- mjolnir/core/SimulatorTraits.hpp
- mjolnir/core/SteepestDescentSimulator.hpp
- mjolnir/core/UnderdampedLangevinIntegrator.hpp
- mjolnir/core/UnlimitedGridCellList.hpp
- mjolnir/core/VelocityVerletIntegrator.hpp
- mjolnir/core/VerletList.hpp
- mjolnir/core/XYZObserver.hpp
- mjolnir/input/read_system.hpp
- mjolnir/interaction/BondAngleInteraction.hpp
- mjolnir/interaction/BondLengthInteraction.hpp
- mjolnir/interaction/DihedralAngleInteraction.hpp
- mjolnir/interaction/ExternalDistanceInteraction.hpp
- mjolnir/interaction/GlobalPairInteraction.hpp
- mjolnir/interaction/specialization/GlobalPairExcludedVolumeInteraction.hpp
- mjolnir/interaction/specialization/GlobalPairLennardJonesInteraction.hpp
- mjolnir/interaction/specialization/GlobalPairUniformLennardJonesInteraction.hpp
- mjolnir/math/Matrix.hpp
- mjolnir/math/Vector.hpp
- mjolnir/math/functions.hpp
- test/mjolnir/test_bond_angle_interaction.cpp
- test/mjolnir/test_bond_length_interaction.cpp
- test/mjolnir/test_dihedral_angle_interaction.cpp
- test/mjolnir/test_math.cpp
- test/mjolnir/test_matrix.cpp
- test/mjolnir/test_vector.cpp
> add math namespace

- mjolnir/core/DCDObserver.hpp
- mjolnir/core/MolecularDynamicsSimulator.hpp
- mjolnir/core/ObserverBase.hpp
- mjolnir/core/SimulatedAnnealingSimulator.hpp
- mjolnir/core/SteepestDescentSimulator.hpp
- mjolnir/core/XYZObserver.hpp
- mjolnir/input/read_observer.hpp
- test/mjolnir/CMakeLists.txt
- test/mjolnir/test_read_observer.cpp
support dcd format as an option for observers.
related to #60 .
> feat: add DCDObserver

- mjolnir/core/ExternalForceField.hpp
- mjolnir/core/ExternalForceInteractionBase.hpp
- mjolnir/core/GlobalForceField.hpp
- mjolnir/core/GlobalInteractionBase.hpp
- mjolnir/core/LocalForceField.hpp
- mjolnir/interaction/ExternalDistanceInteraction.hpp
- mjolnir/interaction/GlobalPairExcludedVolumeInteraction.hpp
- mjolnir/interaction/GlobalPairInteraction.hpp
- mjolnir/interaction/GlobalPairLennardJonesInteraction.hpp
- mjolnir/interaction/GlobalPairUniformLennardJonesInteraction.hpp
- mjolnir/util/logger.hpp
- mjolnir/util/static_string.hpp
- test/mjolnir/test_read_external_forcefield.cpp
- test/mjolnir/test_read_global_forcefield.cpp
- test/mjolnir/test_read_local_forcefield.cpp
- test/mjolnir/test_static_string.cpp
and other refactoring to suppress warnings
> refactor: add const/noexcept specifier

- test/mjolnir/test_read_bond_angle_interaction.cpp
- test/mjolnir/test_read_bond_length_interaction.cpp
- test/mjolnir/test_read_clementi_dihedral_potential.cpp
- test/mjolnir/test_read_debye_huckel_potential.cpp
- test/mjolnir/test_read_dihedral_angle_interaction.cpp
- test/mjolnir/test_read_excluded_volume_potential.cpp
- test/mjolnir/test_read_excluded_volume_wall_potential.cpp
- test/mjolnir/test_read_external_forcefield.cpp
- test/mjolnir/test_read_flexible_local_angle_potential.cpp
- test/mjolnir/test_read_flexible_local_dihedral_potential.cpp
- test/mjolnir/test_read_forcefield.cpp
- test/mjolnir/test_read_global_forcefield.cpp
- test/mjolnir/test_read_global_pair_interaction.cpp
- test/mjolnir/test_read_go_contact_potential.cpp
- test/mjolnir/test_read_harmonic_potential.cpp
- test/mjolnir/test_read_implicit_membrane_potential.cpp
- test/mjolnir/test_read_input_path.cpp
- test/mjolnir/test_read_integrator.cpp
- test/mjolnir/test_read_lennard_jones_potential.cpp
- test/mjolnir/test_read_lennard_jones_wall_potential.cpp
- test/mjolnir/test_read_local_forcefield.cpp
- test/mjolnir/test_read_observer.cpp
- test/mjolnir/test_read_periodic_gaussian_potential.cpp
- test/mjolnir/test_read_simulator.cpp
- test/mjolnir/test_read_system.cpp
- test/mjolnir/test_read_uniform_lennard_jones_potential.cpp
replace initializer_lists in toml::value by toml literals.
> Refactor tests for read_*

- mjolnir/core/AxisAlignedPlane.hpp
- mjolnir/core/EnergyObserver.hpp
- mjolnir/core/PeriodicGridCellList.hpp
- mjolnir/core/SteepestDescentSimulator.hpp
- mjolnir/core/UnlimitedGridCellList.hpp
- mjolnir/core/VelocityVerletIntegrator.hpp
- mjolnir/core/VerletList.hpp
- mjolnir/interaction/external/ExternalDistanceInteraction.hpp
- mjolnir/interaction/global/GlobalPairExcludedVolumeInteraction.hpp
- mjolnir/interaction/global/GlobalPairInteraction.hpp
- mjolnir/interaction/global/GlobalPairLennardJonesInteraction.hpp
- mjolnir/interaction/global/GlobalPairUniformLennardJonesInteraction.hpp
- mjolnir/interaction/local/BondAngleInteraction.hpp
- mjolnir/interaction/local/BondLengthInteraction.hpp
- mjolnir/interaction/local/DihedralAngleInteraction.hpp
replace `system[i].position` by `system.position(i)`.
> use member functions to access physical quantity instead of particle_view

- mjolnir/potential/global/UniformLennardJonesPotential.hpp
- test/omp/test_omp_global_debye_huckel_interaction.cpp
and also, add warn while initializing uniform L-J
> fix incorrect include files in omp test

- mjolnir/input/read_local_interaction.hpp
- mjolnir/input/read_local_potential.hpp
- mjolnir/potential/local/SumLocalPotential.hpp
since it is not so heavily used, I think it is not needed to support an arbitrary number of potentials. This change will increase maintainablity.
> refactor: simplify SumLocalPotential 

- mjolnir/omp/UnlimitedGridCellList.hpp
デバッグフラグを立ててコンパイルしたところエラーになったので。
> fix: lack of logger declaration in debug mode

- book/ja/refs/GlobalPairInteraction.md
- book/ja/refs/HardCoreExcludedVolumePotential.md
- mjolnir/core/GlobalForceField.hpp
- mjolnir/input/read_global_interaction.hpp
- mjolnir/input/read_global_potential.cpp
- mjolnir/input/read_global_potential.hpp
- mjolnir/interaction/global/GlobalPairInteraction.hpp
- mjolnir/potential/global/CMakeLists.txt
- mjolnir/potential/global/ExcludedVolumePotential.hpp
- mjolnir/potential/global/HardCoreExcludedVolumePotential.cpp
- mjolnir/potential/global/HardCoreExcludedVolumePotential.hpp
- test/core/CMakeLists.txt
- test/core/test_excluded_volume_potential.cpp
- test/core/test_hard_core_excluded_volume_potential.cpp
- test/core/test_read_excluded_volume_potential.cpp
- test/core/test_read_hard_core_excluded_volume_potential.cpp
- made hard-core excluded volume potential.
- add descriptions in doc, test for the potential and for the read function.
- inserted some logger descriptions and comment.
- rearrange the input in test for excluded volume function.
> Add hard excluded volume potential

- mjolnir/input/read_forcefield.hpp
- mjolnir/input/read_input_file.hpp
- mjolnir/input/read_integrator.hpp
- mjolnir/input/read_simulator.hpp
- mjolnir/input/read_system.hpp
- mjolnir/input/read_units.hpp
- mjolnir/input/utility.hpp
Warn if unknown keys are provided by users. It is probably a typo.
> check keys in a toml file

- mjolnir/input/read_external_potential.hpp
- mjolnir/potential/external/ExcludedVolumeWallPotential.hpp
- mjolnir/potential/external/ImplicitMembranePotential.hpp
- mjolnir/potential/external/LennardJonesWallPotential.hpp
- test/core/test_excluded_volume_wall_potential.cpp
- test/core/test_implicit_membrane_potential.cpp
- test/core/test_lennard_jones_wall_potential.cpp
- test/core/test_read_excluded_volume_wall_potential.cpp
- test/core/test_read_implicit_membrane_potential.cpp
- test/core/test_read_lennard_jones_wall_potential.cpp
- test/omp/test_omp_external_distance_interaction.cpp
> Refactor external potentials

- mjolnir/input/read_local_interaction.hpp
- test/core/test_read_dihedral_angle_interaction.cpp
> remove harmonic dihedral

- mjolnir/input/read_forcefield.hpp
- mjolnir/input/read_input_file.hpp
- mjolnir/input/read_simulator.cpp
- mjolnir/input/read_simulator.hpp
- mjolnir/input/read_system.hpp
- mjolnir/input/read_table_from_file.cpp
- mjolnir/input/read_table_from_file.hpp
- mjolnir/input/read_units.cpp
- mjolnir/input/read_units.hpp
- test/core/test_read_molecular_dynamics_simulator.cpp
- test/core/test_read_simulated_annealing_simulator.cpp
- test/core/test_read_steepest_descent_simulator.cpp
- test/core/test_read_switching_forcefield_simulator.cpp
- test/core/test_read_unit.cpp
It affects some other tasks, such as #145 .
> Refactor reading table provided by other files

- mjolnir/input/read_local_interaction.hpp
- mjolnir/interaction/local/CMakeLists.txt
- mjolnir/interaction/local/DirectionalContactInteraction.cpp
- mjolnir/interaction/local/DirectionalContactInteraction.hpp
> enable to build directional contact interactions

- CMakeLists.txt
- test/CMakeLists.txt
> chore: add -DBUILD_UNIT_TEST=OFF option to CMake

- mjolnir/forcefield/CMakeLists.txt
- mjolnir/forcefield/PWMcos/CMakeLists.txt
- mjolnir/forcefield/PWMcos/PWMcosInteraction.cpp
- mjolnir/forcefield/PWMcos/PWMcosInteraction.hpp
- mjolnir/forcefield/PWMcos/PWMcosPotential.cpp
- mjolnir/forcefield/PWMcos/PWMcosPotential.hpp
- mjolnir/input/read_global_interaction.hpp
- mjolnir/omp/CMakeLists.txt
- mjolnir/omp/PWMcosInteraction.cpp
- mjolnir/omp/PWMcosInteraction.hpp
- mjolnir/omp/omp.hpp
- test/core/CMakeLists.txt
- test/core/test_pwmcos_interaction.cpp
- test/core/test_pwmcos_potential.cpp
- test/core/test_read_pwmcos_interaction.cpp
- test/omp/CMakeLists.txt
- test/omp/test_omp_global_pwmcos_interaction.cpp
> PWMcos forcefield

- mjolnir/core/Topology.hpp
Now clear() does not clear name or group informations.
> feat: split name and group from nodes

- mjolnir/core/Unit.hpp
> fix: replacement of length unit name and energy unit name

- mjolnir/potential/local/FlexibleLocalDihedralPotential.hpp
Since it makes the minimum energy zero, it requires some initialization
to find the minimum point in the energy function and it takes relatively
long time. Although it does not effect to the overall efficiency because
it would be done only once, still it is painful to wait initialization.
This change caches the minimum energy value and make initialization
faster by look-up min energy that are already calculated.
> perf: speedup initialization of FLP dihedral

- mjolnir/core/Unit.hpp
- mjolnir/forcefield/3SPN2/ThreeSPN2BondPotential.hpp
- mjolnir/input/read_external_interaction.hpp
- mjolnir/input/read_global_interaction.hpp
- mjolnir/input/read_local_interaction.hpp
- mjolnir/interaction/local/BondAngleInteraction.hpp
- mjolnir/interaction/local/BondLengthGoContactInteraction.hpp
- mjolnir/interaction/local/BondLengthInteraction.hpp
- mjolnir/interaction/local/ContactInteraction.hpp
- mjolnir/interaction/local/DihedralAngleInteraction.hpp
- mjolnir/interaction/local/DirectionalContactInteraction.hpp
- mjolnir/interaction/local/GoContactInteraction.hpp
- mjolnir/omp/BondAngleInteraction.hpp
- mjolnir/omp/BondLengthGoContactInteraction.hpp
- mjolnir/omp/BondLengthInteraction.hpp
- mjolnir/omp/DihedralAngleInteraction.hpp
- mjolnir/potential/local/ClementiDihedralPotential.hpp
- mjolnir/potential/local/CosinePotential.hpp
- mjolnir/potential/local/FlexibleLocalAnglePotential.hpp
- mjolnir/potential/local/FlexibleLocalDihedralPotential.hpp
- mjolnir/potential/local/GaussianPotential.hpp
- mjolnir/potential/local/GoContactPotential.hpp
- mjolnir/potential/local/HarmonicPotential.hpp
- mjolnir/potential/local/PeriodicGaussianPotential.hpp
- mjolnir/potential/local/SumLocalPotential.hpp
- mjolnir/potential/local/UniformPotential.hpp
- add initialize function to local potential classes.
- add potential initialize step to the initialize function in local interactions.
- also add to omp version.
> Add initialize2local potentials

- book/ja/SUMMARY.md
- book/ja/refs/BondLengthInteraction.md
- mjolnir/input/read_local_interaction.hpp
- mjolnir/input/read_local_potential.hpp
- mjolnir/potential/local/CMakeLists.txt
- mjolnir/potential/local/WormLikeChainPotential.cpp
- mjolnir/potential/local/WormLikeChainPotential.hpp
- test/core/CMakeLists.txt
- test/core/test_read_worm_like_chain_potential.cpp
- test/core/test_worm_like_chain_potential.cpp
Made new potential based on the worm-like chain model.
This commit contains the implementation, test, and document.
Confirm the agreement between a theoretical distribution and simulated distribution was performed and the result is like the figure.
> Worm like chain potential

- mjolnir/input/read_system.hpp
- mjolnir/input/utility.hpp
- mjolnir/math/Matrix.hpp
enable to do the following.
```cpp
const auto v = toml::find<coordinate_type>(table, "position");
```
> refactor input functions

- mjolnir/forcefield/3SPN2/ThreeSPN2BaseBaseInteraction.hpp
- mjolnir/interaction/local/DihedralAngleInteraction.hpp
- mjolnir/omp/DihedralAngleInteraction.hpp
- mjolnir/omp/ThreeSPN2BaseBaseInteraction.hpp
Note that changes the trajectory because of the numerical error.
> Refactoring and speedup on dihedral angle force calculation

- mjolnir/input/read_integrator.hpp
count function there is the place at function should be.
> fix: read env in BAOABLangevinIntegrator

- mjolnir/core/EnergyObserver.hpp
- mjolnir/core/ExternalForceField.hpp
- mjolnir/core/ForceField.hpp
- mjolnir/core/ForceFieldBase.hpp
- mjolnir/core/GlobalForceField.hpp
- mjolnir/core/LocalForceField.hpp
- mjolnir/forcefield/MultipleBasin/MultipleBasin2BasinUnit.hpp
- mjolnir/forcefield/MultipleBasin/MultipleBasin3BasinUnit.hpp
- mjolnir/forcefield/MultipleBasin/MultipleBasinForceField.hpp
- mjolnir/forcefield/MultipleBasin/MultipleBasinUnitBase.hpp
> refactor: change interface of forcefield to format energies

- CMakeLists.txt
- mjolnir/input/read_input_file.hpp
> Output binary info to log

- book/content.en/docs/reference/forcefields/global/pair/WCAPotential.md
- book/content.ja/docs/reference/forcefields/global/pair/WCAPotential.md
- mjolnir/forcefield/global/CMakeLists.txt
- mjolnir/forcefield/global/WCAPotential.cpp
- mjolnir/forcefield/global/WCAPotential.hpp
- mjolnir/input/read_global_interaction.hpp
- mjolnir/input/read_global_potential.cpp
- mjolnir/input/read_global_potential.hpp
- test/core/CMakeLists.txt
- test/core/test_read_wca_potential.cpp
- test/core/test_wca_potential.cpp
- add Weeks-Chandler-Andersen potential to Pair interaction
> add WCA potential

- mjolnir/omp/CMakeLists.txt
- mjolnir/omp/GJFNVTLangevinIntegrator.cpp
- mjolnir/omp/GJFNVTLangevinIntegrator.hpp
- mjolnir/omp/omp.hpp
support OpenMP parallelization
> parallelize G-JF Langevin Integrator

- test/core/test_excluded_volume_potential.cpp
- test/core/test_inverse_power_potential.cpp
Some small changes for the test.
These changes are for `test_excluded_volume_potential.cpp` and `test_inverse_power_potential.cpp`
> Add log output to some test.

- book/content.en/docs/reference/forcefields/MultipleBasinForceField.md
- book/content.ja/docs/reference/forcefields/MultipleBasinForceField.md
- mjolnir/forcefield/MultipleBasin/MultipleBasin2BasinUnit.hpp
- mjolnir/input/read_forcefield.hpp
- test/core/test_multiple_basin_forcefield.cpp
- test/omp/test_omp_multiple_basin_forcefield.cpp
- enable to restrain χ value in the multiple basin forcefield
> regular monthly update

- mjolnir/util/logger.hpp
to terminate immediately without throwing an exception.
Some functions that normally do not throw any error are marked as
noexcept. But in some cases, the function cannot be calculated or are
kept unimplemented. In such a case, we need a way to halt the simulation
when such a function is called without throwing any error. LOG_FATAL
calls `std::terminate` after showing an error message.
> Add new log level, fatal
