test/mjolnir/test_excluded_volume_potential.cpp

In test_excluded_volume_potential.cpp, template argument of SimulatorTrairsBase in EXV_float should be float. So this is the revision.

fixed template argument of SimulaterTraitsBase in test case of float

---

CMakeLists.txt

CMakeLists assumes that you have "wget" installed, but this requirement is not fulfilled in some systems.

CMakeLists

---

input/implicit_membrane.toml
input/lennard-jones/lennard-jones.toml
input/sh3_AICG2+.toml
input/sh3_AICG2+_periodic.toml
mjolnir/input/read_files_table.hpp
mjolnir/input/read_forcefield.hpp
mjolnir/input/read_input_file.hpp
mjolnir/input/read_observer.hpp
mjolnir/input/read_simulator.hpp
mjolnir/input/read_system.hpp
test/util/make_empty_input.hpp

current status:
```toml
[files]
output_prefix = "foo"
output_path   = "./bar/"
input_path    = "./foo/"
```
this PR:
```toml
[files.output]
prefix = "foo"
path   = "./bar/"
[files.input]
path   = "./foo/"
```
or, after TOML v0.5.0
```toml
[files]
output.prefix = "foo"
output.path   = "./bar/"
input.path    = "./foo/"
```

[files] table in an input file

---

mjolnir/core/ExternalForceInteractionBase.hpp
mjolnir/core/GlobalInteractionBase.hpp
mjolnir/core/LocalInteractionBase.hpp
mjolnir/interaction/ExternalDistanceInteraction.hpp

`ExternalForceField` uses `reconstruct`, but others use `update` to update parameter values.
Use the same name for the consistency.

Use the same name in every ForceFields

---

mjolnir/core/MolecularDynamicsSimulator.hpp
mjolnir/core/ObserverBase.hpp
mjolnir/core/SimulatedAnnealingSimulator.hpp
mjolnir/core/SteepestDescentSimulator.hpp
mjolnir/core/XYZObserver.hpp

XYZObserver doesn't need this, but another file format might require some operations when the simulation is completed.

feat: add finalize to observer

---

mjolnir/math/Matrix.hpp
mjolnir/math/Vector.hpp

Since `operator<<` was broken for a while, the positions/velocities were
formatted weirdly in the log file.

fix: format matrix/vector correctly in logger

---

mjolnir/util/logger.hpp
mjolnir/util/macro.hpp

It seems to be good enough to use `__PRETTY_FUNCTION__` and remove the template names from the name. By applying these changes, the logger can obtain namespace, class name, return value type and argument types. It is longer than `__func__`, which only contains function name, but I think here is the optimal point between the length of the name and the information contained.

feat: make func name in logger long again

---

input/sh3_AICG2+.toml
mjolnir/core/DCDObserver.hpp
mjolnir/core/EnergyObserver.hpp
mjolnir/core/MolecularDynamicsSimulator.hpp
mjolnir/core/ObserverContainer.hpp
mjolnir/core/SimulatedAnnealingSimulator.hpp
mjolnir/core/SteepestDescentSimulator.hpp
mjolnir/core/XYZObserver.hpp
mjolnir/input/read_observer.hpp
test/mjolnir/test_read_observer.cpp

related to #64 .
WIP: This PR will include the following changes.

Organize observers

---

mjolnir/core/RandomNumberGenerator.hpp

`uniform_real_distribution` may call this inside after checking the min/max values. Using this directly, we can avoid needless checking.

feat: use generate_canonical in RNG for real_type

---

mjolnir/core/MolecularDynamicsSimulator.hpp
mjolnir/core/SimulatedAnnealingSimulator.hpp
mjolnir/core/SimulatorBase.hpp
mjolnir/core/SteepestDescentSimulator.hpp
src/mjolnir.cpp

calling `simulator->step()` until it returns `false` is a nice idea to conceal the differences between simulators, but calling this explicitly from `main` is not perfect.
This PR adds `simulator->run()` that currently just call `step()` until the simulation finishes. But, essentially, it will provide more point to hook. It will be useful to have such an interface for other kind of simulation protocols.

feat: add SimulatorBase::run()

---

mjolnir/util/aligned_allocator.hpp
mjolnir/util/aligned_storage.hpp

- `aligned_storage<T, A>`
- `aligned_allocator<T, A>`

Memory alignment support

---

mjolnir/input/read_external_interaction.hpp
mjolnir/input/read_external_potential.hpp
mjolnir/interaction/external/PositionRestraintInteraction.hpp
mjolnir/potential/external/HarmonicRestraintPotential.hpp
test/mjolnir/CMakeLists.txt
test/mjolnir/test_harmonic_restraint_potential.cpp
test/mjolnir/test_position_restraint_interaction.cpp
test/mjolnir/test_read_harmonic_restraint_potential.cpp
test/mjolnir/test_read_position_restraint_interaction.cpp

add the following feature.
- `PositionRestraintInteraction`
- a kind of external interaction. It restrains a particle at a fixed position.
- `HarmonicRestraintPotential`
- a kind of external potential. It has parameters like spring constant and native length for each particle.

Add Harmonic Position Restraint

---

mjolnir/input/read_local_interaction.hpp
mjolnir/interaction/local/BondAngleInteraction.hpp
mjolnir/interaction/local/ContactInteraction.hpp
mjolnir/math/constants.hpp
mjolnir/potential/local/ClementiDihedralPotential.hpp
mjolnir/potential/local/FlexibleLocalAnglePotential.hpp
mjolnir/potential/local/FlexibleLocalDihedralPotential.hpp
mjolnir/potential/local/GaussianPotential.hpp
mjolnir/potential/local/GoContactPotential.hpp
mjolnir/potential/local/HarmonicPotential.hpp
mjolnir/potential/local/PeriodicGaussianPotential.hpp
mjolnir/potential/local/SumLocalPotential.hpp
test/mjolnir/CMakeLists.txt
test/mjolnir/test_contact_interaction.cpp

Add `ContactInteraction`.
It is basically the same as `BondLengthInteraction`, but it has a kind of neighbor-list and skips contacts that the particles are more distant than the cutoff range.

ContactInteraction

---

mjolnir/input/read_input_file.hpp

The important flags, such as `precision` and `boundary_type`, are defined in the `[simulator]` table.
Those flags must be read before reading other settings. Reading [simulator] before others makes  initialization a bit faster, especially in the case if [simulator] is splitted from the main file.

refactor: read [simulator] before calling readers

---

mjolnir/util/aligned_allocator.hpp

fix `rebind`. Consider the `Alignment` value when rebinding it to other types.
Most of the containers use `rebind`, so this bug makes incompatibility with STL containers.

Fix aligned allocator

---

mjolnir/interaction/global/GlobalPairExcludedVolumeInteraction.hpp
mjolnir/interaction/global/GlobalPairLennardJonesInteraction.hpp
mjolnir/interaction/global/GlobalPairUniformLennardJonesInteraction.hpp

The current implementation is not capable to specialize for both `Potential` and `Traits`.

refactor: make specialization pattern strict

---

mjolnir/core/AxisAlignedPlane.hpp
mjolnir/core/NaivePairCalculation.hpp
mjolnir/core/PeriodicGridCellList.hpp
mjolnir/core/Plane.hpp
mjolnir/core/UnlimitedGridCellList.hpp
mjolnir/core/VerletList.hpp
mjolnir/interaction/external/ExternalDistanceInteraction.hpp
mjolnir/interaction/global/GlobalPairExcludedVolumeInteraction.hpp
mjolnir/interaction/global/GlobalPairInteraction.hpp
mjolnir/interaction/global/GlobalPairLennardJonesInteraction.hpp
mjolnir/interaction/global/GlobalPairUniformLennardJonesInteraction.hpp
mjolnir/omp/ExternalDistanceInteraction.hpp
mjolnir/omp/GlobalPairDebyeHuckelInteraction.hpp
mjolnir/omp/GlobalPairExcludedVolumeInteraction.hpp
mjolnir/omp/GlobalPairLennardJonesInteraction.hpp
mjolnir/omp/GlobalPairUniformLennardJonesInteraction.hpp
mjolnir/omp/PeriodicGridCellList.hpp
mjolnir/omp/UnlimitedGridCellList.hpp

Currently, most of the implementation of `reconstruction` just call `initialize`. It replaces `reconstruct` by re-`initialize`.

Refactor: remove reconstruction

---

mjolnir/omp/GlobalPairInteraction.hpp
mjolnir/omp/omp.hpp

At first, this partial specialization conflicts with default
implementation of L-J and EXV, so I made the condition strict (exact
match with Debye-Huckel). But now the specialization conditions of the
default implementation of L-J and EXV are relaxed, I also relax the
condition here.
This change will reduce the implementation cost of global pair
potentials.

refactor: relax specialization condition

---

mjolnir/omp/ForceField.hpp
mjolnir/omp/System.hpp
mjolnir/omp/UnderdampedLangevinIntegrator.hpp
mjolnir/omp/omp.hpp

In the current OpenMP implementation, integrators need to take care that `calc_force` to make sure that it runs inside of `omp parallel` section and it merges all the thread-local forces into the "main" forces.
It is not a good design because it breaks the single responsibility principle. To calculate force correctly, not only the Forcefield but also an Integrator need to know how to do that.
Actually, I found a potential bug caused by this bad design. If someone implements a new interaction or a new integrator class that does not support OpenMP and then the one combine it to the current OpenMP implementation, the other integrator and forcefield ignore the interaction.
This PR fixes that design issue by putting all the stuff required to calculate force into ForceField.

do all the related stuff in ForceField::calc_force

---

mjolnir/input/read_external_potential.hpp
mjolnir/input/read_global_potential.hpp
mjolnir/input/read_local_potential.hpp
mjolnir/input/utility.hpp
test/core/test_read_clementi_dihedral_potential.cpp
test/core/test_read_debye_huckel_potential.cpp
test/core/test_read_excluded_volume_potential.cpp
test/core/test_read_excluded_volume_wall_potential.cpp
test/core/test_read_flexible_local_angle_potential.cpp
test/core/test_read_flexible_local_dihedral_potential.cpp
test/core/test_read_gaussian_potential.cpp
test/core/test_read_go_contact_potential.cpp
test/core/test_read_harmonic_potential.cpp
test/core/test_read_harmonic_restraint_potential.cpp
test/core/test_read_implicit_membrane_potential.cpp
test/core/test_read_lennard_jones_potential.cpp
test/core/test_read_lennard_jones_wall_potential.cpp
test/core/test_read_periodic_gaussian_potential.cpp
test/core/test_read_uniform_lennard_jones_potential.cpp

This PR enables to define variables that can be used in the force-field parameter.
```toml
[[forcefields.local]]
env.large = 100.0
parameters = [
{indices = [0, 1], k = "large"}, # k becomes 100.0
]
```
It would be useful to reduce file size and improve readability in some cases.

#113 :alembic: Enable to define variable

---

.travis.yml
mjolnir/omp/PeriodicGridCellList.hpp
mjolnir/omp/UnlimitedGridCellList.hpp
mjolnir/omp/sort.hpp
mjolnir/util/logger.hpp

When it is used with a potential that is applied to not all the particles, it causes an error and the simulation explodes.
Global potentials that are applied to all the particles, such as Lennard-Jones, are not affected by this bug.

fix openmp implementations of cell lists

---

mjolnir/core/NaivePairCalculation.hpp
mjolnir/core/NeighborList.hpp
mjolnir/core/PeriodicGridCellList.hpp
mjolnir/core/UnlimitedGridCellList.hpp
mjolnir/core/VerletList.hpp
mjolnir/forcefield/3SPN2/ThreeSPN2BaseBaseInteraction.hpp
mjolnir/forcefield/3SPN2/ThreeSPN2BaseBaseInteractionPotential.hpp
mjolnir/forcefield/3SPN2/ThreeSPN2ExcludedVolumePotential.hpp
mjolnir/interaction/global/GlobalPairExcludedVolumeInteraction.hpp
mjolnir/interaction/global/GlobalPairInteraction.hpp
mjolnir/interaction/global/GlobalPairLennardJonesInteraction.hpp
mjolnir/interaction/global/GlobalPairUniformLennardJonesInteraction.hpp
mjolnir/omp/GlobalPairExcludedVolumeInteraction.hpp
mjolnir/omp/GlobalPairInteraction.hpp
mjolnir/omp/GlobalPairLennardJonesInteraction.hpp
mjolnir/omp/GlobalPairUniformLennardJonesInteraction.hpp
mjolnir/omp/ThreeSPN2BaseBaseInteraction.hpp
mjolnir/potential/global/DebyeHuckelPotential.hpp
mjolnir/potential/global/ExcludedVolumePotential.hpp
mjolnir/potential/global/HardCoreExcludedVolumePotential.hpp
mjolnir/potential/global/LennardJonesPotential.hpp
mjolnir/potential/global/UniformLennardJonesPotential.hpp
test/core/test_periodic_cell_list.cpp
test/core/test_periodic_verlet_list.cpp
test/core/test_unlimited_cell_list.cpp
test/core/test_unlimited_verlet_list.cpp

related to #153 and #161; to support such kinds of interactions in the fastest and simplest way.
The interaction implemented in #161 can be implemented without this, but implementing it without this change requires to re-implement Verlet list that is specific to the interaction and it might slow down the simulation. Also, this PR makes the input table consistent with other global interactions.

split participants into two, left and right sides in the pair list

---

mjolnir/core/AxisAlignedPlane.hpp
mjolnir/input/read_external_interaction.hpp
mjolnir/input/read_system.hpp
mjolnir/omp/sort.hpp
test/core/test_axis_aligned_plane_shape.cpp
test/core/test_read_external_forcefield.cpp
test/integration/test_BAOABIntegrator/test_BAOABIntegrator.cpp
test/omp/test_omp_external_distance_interaction.cpp

- always use `math::X` and others instead of `operator[]`.
- always use `math::make_coordinate` instead of `coordinate_type(1,2,3)`
- refactor AxisAlignedPlane a bit

refactor: math vector related stuffs and AxisAlignedPlane

---

mjolnir/input/CMakeLists.txt
mjolnir/input/read_integrator.hpp
mjolnir/input/read_random_number_generator.cpp
mjolnir/input/read_random_number_generator.hpp
mjolnir/input/read_simulator.cpp
mjolnir/input/read_simulator.hpp
mjolnir/input/read_units.hpp
test/core/test_read_molecular_dynamics_simulator.cpp
test/core/test_read_simulated_annealing_simulator.cpp
test/core/test_read_steepest_descent_simulator.cpp
test/core/test_read_switching_forcefield_simulator.cpp

- add `read_random_number_generator.?pp`
- add `read_integrator_type` to determine which integrator to be used
- this simplify each `read_xxx_simulator` but increases number of template instances
- add test code related to `read_integrator_type`

refactoring: read_simulator

---

mjolnir/potential/local/UniformPotential.hpp

There is a mistake in the coefficient of uniform potential.

fix: comment about coefficient of uniform potential

---

mjolnir/input/read_global_potential.hpp

warn if a wrong key is defined.

feat: check names of keys defined in global.ignore

---

mjolnir/input/read_global_potential.hpp

It's better to see `ignore.particle_within` status in a terminal.

feat: change ignore_particle status info -> notice

---

src/mjolnir.cpp

- Move total time display from stdout to stderr.
- Adapt time representation to sec~day style.

feat: imporve total time representation

---

mjolnir/core/BoundaryCondition.hpp
mjolnir/core/CMakeLists.txt
mjolnir/core/MsgPackObserver.cpp
mjolnir/core/MsgPackObserver.hpp
mjolnir/input/read_observer.hpp
mjolnir/input/read_system.hpp
mjolnir/util/macro.hpp
test/core/CMakeLists.txt
test/core/test_read_observer.cpp
test/core/test_save_load_msgpack.cpp
test/omp/CMakeLists.txt
test/omp/test_omp_save_load_msgpack.cpp

Make it easier to start a simulation from the last snapshot of another trajectory.
In the current implementation,
- output `filename.msg`
- by specifying `file_name = "filename.msg"` in `[[systems]]` table, the snapshot will be loaded.

Enable restarting via msgpack file

---

mjolnir/input/read_global_potential.hpp
mjolnir/input/read_integrator.hpp
mjolnir/input/read_simulator.hpp
mjolnir/input/utility.hpp

The list of the changed point is below.
1. add offset to each read integrator function.
2. add env to each read integrator function.
3. avoid raising warning from check_key_available.
4. check the duplicated definition of gamma to the same index in read_underdamped_langevin_integrator function.
Using offset for parameter definition, the possibility of mistakes about index increases, so I implemented the fourth point. However, how to implement this is not trivial to me.
Now, UnderdampedLangevimIntegrator uses the real type vector to store the gamma and I have no idea to check duplicated definition based on this without another container. One option to implement a method is changing gamma container to another type of container, but this change is too large.
I implemented it using a temporal …

enable to use env and offset in simulator table

---

mjolnir/forcefield/global/DebyeHuckelPotential.hpp
mjolnir/input/read_external_interaction.hpp
mjolnir/input/read_external_potential.hpp
mjolnir/input/read_forcefield.hpp
mjolnir/input/read_global_interaction.hpp
mjolnir/input/read_global_potential.hpp
mjolnir/input/read_input_file.hpp
mjolnir/input/read_integrator.hpp
mjolnir/input/read_local_interaction.hpp
mjolnir/input/read_local_potential.hpp
mjolnir/input/read_observer.hpp
mjolnir/input/read_path.hpp
mjolnir/input/read_simulator.hpp
mjolnir/input/read_system.hpp
mjolnir/input/read_table_from_file.cpp
mjolnir/input/read_table_from_file.hpp
mjolnir/input/utility.hpp
test/core/test_debye_huckel_potential.cpp

- enable to use offset and env in `[simulator]` table (@yutakasi634 )
- check parameter duplication in `[simulator]` (@yutakasi634 )
- enable to include toml files in a input file
The included files will be expanded only once. Recursive inclusion does not work.
```toml
include = "some_table.toml"
[another_table]
include = ["parameter1.toml", "parameter2.toml"]
```

regular monthly update

---

book/ja/refs/ExcludedVolumeWallPotential.md

In ExcludedVolumeWallPotential reference, the argument of the potential parameter is "ExcludedVolume" but Mjolnir raise an error "[error] mjolnir::read_external_distance_interaction: invalid potential".

doc: fix potential parameter argument in ExcludedVolumeWall

---

mjolnir/input/read_input_file.hpp
mjolnir/input/utility.hpp
test/core/CMakeLists.txt
test/core/test_file_inclusion.cpp

- enable to expand an include file inside an array of tables.
- avoid unexpected recursive inclusion when including the following file
```toml
[foo]
include = "include.toml"
```

fix: input file inclusion

---

mjolnir/input/read_local_potential.hpp
test/core/test_read_index_offset.cpp

This change is only for local potential.
- Offset becomes to accept list, and if get the list, each element of the list is added to the corresponding element of the indices list.
For example, 
```
...
{indices = [ 0, 1], ... , offset = [ 1, 2]},
...
```
from the above file, indices are finally interpreted to `[ 1, 3]`.
- If the size of a given offset list don't match that of the indices list, the reading process raises a runtime error.

enable to pass list of offset to input.

---

mjolnir/core/NeighborList.hpp
mjolnir/core/PeriodicGridCellList.hpp
mjolnir/core/UnlimitedGridCellList.hpp
mjolnir/omp/PeriodicGridCellList.hpp
mjolnir/omp/UnlimitedGridCellList.hpp

Current implementation requires too many allocations and it slows down the simulation. It is only executed once, at the first step, but still it can impact on the total simulation time, especially for a short simulation. This PullReq reduces the allocation calls by approximating the total amount of memory region that would be used.

avoid frequent memory allocations in neighborlist

---

mjolnir/input/read_global_potential.hpp

Currently, only global interaction does not allow negative offset in the input file.

fix: allow negative offset in global potentials

---

mjolnir/util/fixed_vector.hpp

`bad_alloc` should be able to construct without memory, so it does not have region to store a string.

fix: remove message from bad_alloc construction in fixed_vector

---

mjolnir/util/fixed_vector.hpp
test/core/test_3spn2_base_base_interaction.cpp
test/core/test_afm_fitting_interaction.cpp

Currently, fixed_vector::at does not throw out_of_range.

Throw out_of_range correctly

---

mjolnir/core/NaivePairCalculation.hpp
mjolnir/core/PeriodicGridCellList.hpp
mjolnir/core/SpatialPartitionBase.hpp
mjolnir/core/UnlimitedGridCellList.hpp
mjolnir/core/VerletList.hpp
mjolnir/core/ZorderRTree.hpp
mjolnir/omp/PeriodicGridCellList.hpp
mjolnir/omp/UnlimitedGridCellList.hpp

The global interaction which I'm implementing now (https://github.com/Mjolnir-MD/Mjolnir/pull/236) needs the information that the neighbor list is updated or not in the current simulation step.
The interaction, which is based on GlobalInteractionBase, calls reduce_margin of SpatialPartiion, so, in this PR, I enable this reduce_margin method can notify that information via returned bool value.

feat: enable reduce_margin to return bool

---

.github/workflows/build.yml
CMakeLists.txt

Boost seems to be removed from ubuntu-18 image on GitHub Actions.
This should fix #282 .

Update ci settings

---

mjolnir/core/DCDLoader.hpp
mjolnir/input/read_simulator.hpp

Some of the error messages shown in the following cases are improved.
- Warning about explicitly initialized positions and velocities in `EnergyCalculation` simulator which overwrite the system coordinates by a state loaded from a specified file
- Warning about inconsistent block in a DCD file
- Suppress incorrect warnings that appears when `DCDLoader` reaches to the end of a file

fix: make error message concise

---

mjolnir/core/DCDObserver.hpp
mjolnir/core/EnergyCalculationSimulator.hpp
mjolnir/core/EnergyObserver.hpp
mjolnir/core/MolecularDynamicsSimulator.hpp
mjolnir/core/ObserverBase.hpp
mjolnir/core/ObserverContainer.hpp
mjolnir/core/SimulatedAnnealingSimulator.hpp
mjolnir/core/SteepestDescentSimulator.hpp
mjolnir/core/SwitchingForceFieldSimulator.hpp
mjolnir/core/TRRObserver.hpp
mjolnir/core/XYZObserver.hpp

fixes #289 .
Since other file format does not require save step interval, it currently output a dummy value, 0. But there exist some tool that requires the value and a dummy value will cause a problem in that case.

feat: enable to write save_interval in dcd file header

---

test/integration/test_G-JF_Integrator/.gitignore

I noticed the other integration tests have a .gitignore file. Thus, I added one for the G-JF Integrator test.

add gitignore for G-JF Integrator integration test

---

CMakeLists.txt

Recently, boost has changed its URL.  On their webpage, there is a notice indicating:
...
Instead of: https://dl.bintray.com/boostorg/release/ you should use https://boostorg.jfrog.io/artifactory/main/release/ to retrieve boost releases.
...
(https://www.boost.org/users/news/boost_has_moved_downloads_to_jfr.html)
This commit updates the URL in the CMake file.

update boost url

---

.github/workflows/document.yml
CHANGELOG.md
book/content.en/docs/reference/forcefields/MultipleBasinForceField.md
book/content.ja/docs/reference/forcefields/MultipleBasinForceField.md
mjolnir/core/BAOABLangevinIntegrator.hpp
mjolnir/core/GFWNPTLangevinIntegrator.hpp
mjolnir/core/GJFNVTLangevinIntegrator.hpp
mjolnir/core/UnderdampedLangevinIntegrator.hpp
mjolnir/core/VelocityVerletIntegrator.hpp
mjolnir/core/gBAOABLangevinIntegrator.hpp
mjolnir/omp/BAOABLangevinIntegrator.hpp
mjolnir/omp/GFWNPTLangevinIntegrator.hpp
mjolnir/omp/GJFNVTLangevinIntegrator.hpp
mjolnir/omp/UnderdampedLangevinIntegrator.hpp
mjolnir/omp/gBAOABLangevinIntegrator.hpp

`set_delta_t` does not work when an integrator requries a parameter, like mass of particles. This adds `update(sys, newdt)` to enable integrators to update delta t.

Enable to update dt

---

mjolnir/forcefield/global/ParameterList.hpp
mjolnir/input/read_global_potential.hpp
test/core/test_read_forcefield.cpp
test/core/test_read_global_forcefield.cpp
test/core/test_read_hybrid_forcefield.cpp
test/core/test_read_multiple_basin_forcefield.cpp

When using UniformLennardJonesPotential or UniformCubicPanPotential, if the parameters table is empty, the leading_participants function of EmptyCombinationRule returns the range in which the begin and end positions are the same. This makes segmentation fault errors in runtime.
In the no parameters case of these potentials, all particles in the system are considered participants. Based on this, I made the empty parameter case also considered all particles as participants, and raise warnings similar to the previous version of Mjolnir.
I don't know the correct behavior of the empty parameters table case, so if this is not appropriate, I'm sorry about that.

Fix read uniform global potential
